<?php


// Firebase API Key
define('FIREBASE_API_KEY', 'AAAA7ptVEA4:APA91bErPt6Zq1NhntYjA4NnJpPUCs9nRULn9Xzo3VPVLGsDI-SZLmedO12RELbDrLuXezqeY9OlLRE7bLZSPUzAIQdxnS8X-GBM04YI6JEkTsFLLlRXL4IzSlwQesub1DdImYdugPEbhPxNTbpuTZ7KyCdLynB8eQ');
